service: lambda-test

provider:
  name: aws
  runtime: nodejs6.10

functions:
  testFunction:
    handler: handler.testFunction
    events:
      - http:
          path: test-lambda/hello
          method: get
